version: '3'

includes:
  vm: ./vm
  darwin: ./darwin

tasks:
  fmt:
    cmds:
      - nix fmt
  check:
    cmds:
      - nix flake check
  eval:
    cmds:
      - nix eval --offline --read-only .#nixosConfigurations.salome.config.system.build.toplevel.drvPath
      - nix eval --offline --read-only .#nixosConfigurations.aida.config.system.build.toplevel.drvPath
      - nix eval --offline --read-only .#nixosConfigurations.attila.config.system.build.toplevel.drvPath
      - nix eval --offline --read-only .#nixosConfigurations.vm-iso.config.system.build.toplevel.drvPath
      - nix eval --offline --read-only .#darwinConfigurations.cesare.system
