(provide 'python)

(defun python-pretty-lambda ()
  (setq prettify-symbols-alist
        '(("lambda" . ?λ)
	  ("sum"    . ?Σ)
	  ("="      . ?←)
	  ("=="     . ?≡)
	  ("!="     . ?≠)
	  ("<="     . ?≤)
	  (">="     . ?≥)
	  ("for"    . ?∀)
	  ("if"     . ?∃)
	  ("not"    . ?¬)
	  ("or"     . ?∨)
	  ("and"    . ?∧)
	  ("True"   . ?⊤)
	  ("False"  . ?⊥)
	  ("None"   . ?∅)
	  ("self"   . ?◎)
	  ("import" . ?≺)
	  (":"      . ?▶)
	  ("\\"     . ?…)
	  ("def"    . ?§)
	  ("class"  . ?⌘)
	  ("return" . ?◀)
	  ("*"      . ?×)
	  ("^"      . ?⊕)
	  ("/"      . ?÷))))

(add-hook 'python-mode-hook
          (lambda ()
	    (python-pretty-lambda)
	    ;(prettify-symbols-mode +1)
	    ))
