# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  # UPGRADE: This was removed from vmware-guest at some point; check
  # if it is back in the next upgrade
  services.xserver.videoDrivers = lib.mkOverride 50 [ "vmware" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/09442904-1c08-47dd-b3ad-7d1cd6e64e9b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/57AD-7975";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/216428c4-b061-49f5-b97a-60d4c6ea179f"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 8;
}
