version: '3'

vars:
  ROOT:
    sh: git rev-parse --show-toplevel

tasks:
  nix:
    cmds:
      - curl -fsSL https://install.determinate.systems/nix | sh -s -- install --no-confirm
    status:
      - type nix

  bootstrap:
    cmds:
      - sudo nix run nix-darwin/nix-darwin-25.05#darwin-rebuild -- switch --flake .#$(hostname)
      - sudo mkdir /etc/nix-darwin/
      - sudo ln -s {{.ROOT}}/flake.nix /etc/nix-darwin/flake.nix
    status:
      - darwin-version

  update-keyboard:
    cmds:
      - ./{{.ROOT}}/darwin/keyboard-to-nix.sh > darwin/keyboard.nix

  # TODO: find a way to reset the context between these steps so binaries get onto the path
  install:
    cmds:
      - task: nix
      - task: bootstrap
      - task: default

  default:
    cmds:
      - sudo darwin-rebuild switch
