(provide 'python-lang)

(ensure-packages-installed 'python-mode 'lsp-pyright 'company)

(require 'lsp-mode)
(require 'lsp-pyright)

(setq lsp-completion-provider :capf)

(defun python-pretty-lambda ()
  (setq prettify-symbols-alist
        '(("lambda" . ?λ)
	  ("sum"    . ?Σ)
	  ("="      . ?←)
	  ("=="     . ?≡)
	  ("!="     . ?≠)
	  ("<="     . ?≤)
	  (">="     . ?≥)
	  ("for"    . ?∀)
	  ("if"     . ?∃)
	  ("not"    . ?¬)
	  ("or"     . ?∨)
	  ("and"    . ?∧)
	  ("True"   . ?⊤)
	  ("False"  . ?⊥)
	  ("None"   . ?∅)
	  ("self"   . ?◎)
	  ("import" . ?≺)
	  (":"      . ?▶)
	  ("\\"     . ?…)
	  ("def"    . ?§)
	  ("class"  . ?⌘)
	  ("return" . ?◀)
	  ("*"      . ?×)
	  ("^"      . ?⊕)
	  ("/"      . ?÷))))

(add-hook 'python-mode-hook
          (lambda ()
	    (python-pretty-lambda)
	    (prettify-symbols-mode +1)
	    (define-key python-mode-map (kbd "C-c f") 'python-shell-send-file)
	    (setq company-minimum-prefix-length 1)
	    ;; (setq lsp-file-watch-threshold nil)
	    (lsp-deferred)))
