# Immich — self-hosted Google Photos replacement.
#
# Runs as four containers (server, ML worker, Postgres with pgvecto-rs, Redis).
# Pin versions deliberately; Immich's DB migrations are version-coupled and
# skipping versions can corrupt the database.
#
# VAAPI (hardware video transcoding via the Ryzen 5 3500U's Vega 8 iGPU):
# The renderD128 device is passed through to the server container. Verify
# with `ls -la /dev/dri/` — if renderD128 is absent, check kernel modules
# (amdgpu should be loaded: `lsmod | grep amdgpu`).
#
# First-run checklist:
#   1. Navigate to https://immich.yourdomain.com and create the admin account.
#   2. Install the Immich mobile app and add the server URL.
#   3. Enable auto-backup in the app. Initial ML indexing will take hours.

{ config, ... }:

let
  # Pin to a specific release. Check https://github.com/immich-app/immich/releases
  # before upgrading — never skip major versions.
  immichVersion = "v1.131.0";
  dataDir = "/data/immich";
in

{
  # amdgpu kernel module is needed for VAAPI on Vega 8
  boot.kernelModules = [ "amdgpu" ];

  hardware.graphics = {
    enable = true;
    extraPackages = with (import <nixpkgs> {}).pkgs; [
      amdvlk
      rocm-opencl-icd
      rocm-opencl-runtime
    ];
  };

  # Grant the render group access; Podman maps this into containers that
  # request the /dev/dri/renderD128 device.
  users.groups.render = {};
  users.groups.video = {};

  virtualisation.oci-containers.containers = {

    immich-server = {
      image = "ghcr.io/immich-app/immich-server:${immichVersion}";
      # Bind to localhost; Caddy terminates TLS and proxies here
      ports = [ "127.0.0.1:2283:2283" ];
      volumes = [
        "${dataDir}/upload:/usr/src/app/upload"
        "/etc/localtime:/etc/localtime:ro"
      ];
      environment = {
        DB_HOSTNAME = "127.0.0.1";
        DB_USERNAME = "immich";
        DB_DATABASE_NAME = "immich";
        REDIS_HOSTNAME = "127.0.0.1";
        IMMICH_VERSION = immichVersion;
      };
      environmentFiles = [
        # Contains: DB_PASSWORD=<value of immich/db-password secret>
        # Generated by a small activation script; see below.
        "/run/immich-env"
      ];
      extraOptions = [
        "--network=host"
        # VAAPI hardware transcoding
        "--device=/dev/dri/renderD128:/dev/dri/renderD128"
        "--group-add=render"
        "--group-add=video"
      ];
    };

    immich-machine-learning = {
      image = "ghcr.io/immich-app/immich-machine-learning:${immichVersion}";
      volumes = [ "${dataDir}/cache:/cache" ];
      environment = {
        IMMICH_VERSION = immichVersion;
      };
      extraOptions = [ "--network=host" ];
    };

    immich-postgres = {
      # pgvecto-rs is required for Immich's vector similarity search
      image = "tensorchord/pgvecto-rs:pg14-v0.2.0";
      volumes = [ "${dataDir}/db:/var/lib/postgresql/data" ];
      environment = {
        POSTGRES_USER = "immich";
        POSTGRES_DB = "immich";
        POSTGRES_INITDB_ARGS = "--data-checksums";
      };
      environmentFiles = [ "/run/immich-env" ];
      extraOptions = [ "--network=host" ];
    };

    immich-redis = {
      image = "docker.io/library/redis:6.2-alpine";
      extraOptions = [ "--network=host" ];
    };

  };

  # Write a runtime env file containing the DB password from sops.
  # This avoids passing the secret via an environment variable in the Nix store.
  systemd.services.immich-env-setup = {
    description = "Write Immich runtime environment file";
    before = [
      "podman-immich-server.service"
      "podman-immich-postgres.service"
    ];
    wantedBy = [
      "podman-immich-server.service"
      "podman-immich-postgres.service"
    ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      DB_PASSWORD=$(cat ${config.sops.secrets."immich/db-password".path})
      printf 'DB_PASSWORD=%s\nPOSTGRES_PASSWORD=%s\n' "$DB_PASSWORD" "$DB_PASSWORD" \
        > /run/immich-env
      chmod 600 /run/immich-env
    '';
  };
}
