name: Notify git-sync subscribers

on:
  push:
    branches: [master]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -sf \
            -u "git-sync:${{ secrets.NTFY_GIT_SYNC_PASSWORD }}" \
            -d "config pushed: ${{ github.sha }}" \
            https://ntfy.malloc47.com/git-sync
